<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classdiagrams" nsURI="http://soton.ac.uk/models/eventb/classdiagrams/2015"
    nsPrefix="classdiagrams">
  <eClassifiers xsi:type="ecore:EClass" name="ClassdiagramOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classdiagrams" upperBound="-1"
        eType="#//Classdiagram" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classdiagram" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBNamedCommentedElement ../../org.eventb.emf.core/model/eventbcore.ecore#//AbstractExtension ../../ac.soton.eventb.emf.diagrams/model/diagrams.ecore#//Diagram">
    <eAnnotations source="org.eventb.emf.core.extendedMetaClasses" references="../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Machine ../../org.eventb.emf.core/model/eventbcore.ecore#//context/Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//Classdiagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="../../ac.soton.eventb.emf.core.extension/model/eventbcoreextension.ecore#//EventBNamedCommentedRelationDataElaborationElement #//EventBInitialisable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isAssociationTypeRight"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAttribute" eSuperTypes="../../ac.soton.eventb.emf.core.extension/model/eventbcoreextension.ecore#//EventBNamedCommentedRelationDataElaborationElement #//EventBInitialisable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="../../ac.soton.eventb.emf.core.extension/model/eventbcoreextension.ecore#//EventBNamedCommentedDataElaborationElement ../../ac.soton.eventb.emf.diagrams/model/diagrams.ecore#//DiagramOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classAttributes" upperBound="-1"
        eType="#//ClassAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//Class">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="parentIsNotConstant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ClassConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//ClassMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selfName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMethod" eSuperTypes="../../ac.soton.eventb.emf.core.extension/model/eventbcoreextension.ecore#//EventBCommentedLabeledEventGroupElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//MethodKind"
        defaultValueLiteral="normal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassConstraint" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBNamedCommentedDerivedPredicateElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MethodKind">
    <eLiterals name="normal"/>
    <eLiterals name="constructor" value="1"/>
    <eLiterals name="destructor" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventBInitialisable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
