<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachines"
    nsURI="http://soton.ac.uk/models/eventb/statemachines" nsPrefix="statemachines">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStatemachine" abstract="true"
      eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBCommentedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="rootHasInitial&#xA;hasAtMostOneInitial&#xA;hasAtMostOneFinal&#xA;hasInitialIfIncomingExternal&#xA;hasInitialIfOutgoingLocal"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBCommentedElement #//EventBLabeled">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="notToInitial&#xA;notFromFinal&#xA;notFromInitialToFinal&#xA;elaboratesOnRootIfInitial&#xA;elaboratesOnRootIfFinal&#xA;elaboratesOnNestedIfNotInitialOrFinal"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elaborates" upperBound="-1"
        eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceContainer" eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//EventBElement"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetContainer" eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//EventBElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operations" transient="true">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefinedStatemachine" eSuperTypes="#//DiagramRoot #//EventBLabeled ../../org.eventb.emf.core/model/eventbcore.ecore#//AbstractExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasNoStates"/>
    </eAnnotations>
    <eAnnotations source="org.eventb.emf.core.extendedMetaClasses" references="../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Machine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" lowerBound="1"
        eType="#//AbstractStatemachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statemachine" eSuperTypes="#//DiagramRoot ../../org.eventb.emf.core/model/eventbcore.ecore#//EventBNamed ../../org.eventb.emf.core/model/eventbcore.ecore#//AbstractExtension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasNoRefinedStates"/>
    </eAnnotations>
    <eAnnotations source="org.eventb.emf.core.extendedMetaClasses" references="../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Machine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="translation" eType="#//TranslationKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TranslationKind">
    <eLiterals name="MULTIVAR"/>
    <eLiterals name="SINGLEVAR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventBLabeled" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//AbstractState ../../org.eventb.emf.core/model/eventbcore.ecore#//EventBNamed">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasNoRefinedStatemachines"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initial" eSuperTypes="#//AbstractNode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasOutgoingOnRoot&#xA;hasOutgoingOnNestedIfExternalIncoming"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANY" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Final" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatemachineOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statemachines" upperBound="-1"
        eType="#//AbstractStatemachine" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefinedState" eSuperTypes="#//AbstractState #//EventBLabeled">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" lowerBound="1"
        eType="#//AbstractState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true" eSuperTypes="#//AbstractNode #//StatemachineOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Invariant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramRoot" eSuperTypes="#//AbstractStatemachine"/>
</ecore:EPackage>
